# Generated by Django 5.2.8 on 2025-11-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Владелец'), ('TEACHER', 'Учитель'), ('STUDENT', 'Ученик')], default='STUDENT', max_length=10, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='courses_enrolled',
            field=models.ManyToManyField(blank=True, related_name='students', to='users.course', verbose_name='Курсы, на которые записан'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='courses_taught',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='users.course', verbose_name='Курсы, которые преподает'),
        ),
    ]
