# Generated by Django 5.2.8 on 2025-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_course_customuser_role_customuser_courses_enrolled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='courses_enrolled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='courses_taught',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('STUDENT', 'Ученик')], default='STUDENT', max_length=10, verbose_name='Роль'),
        ),
    ]
