# Generated by Django 5.2.8 on 2025-12-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_submission_submissionfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentteacherassignment',
            unique_together={('student', 'teacher', 'course')},
        ),
    ]
